
export default {
  mainPage: 'index',
  searchColor: 'search-color',
  colorDetail: 'color-detail',
  colorList: 'color-list',
  fetchColorDetail: 'fetch-color-detail',
  compareColor: 'compare-color',
  bindPhone: 'bind-phone',
  webview: 'webview',
  inputCode: 'input-code',
  deviceManager: 'device-manager',
  connectDevice: 'connect-device',
  applyResult: 'apply-result',
  colorLibraryDetail: 'color-library-detail',
  settingTag: 'setting-tag',
  joinLibrary: 'join-library',
  addLibrary: 'add-library',
  favoriteLibrary: 'favorite-library',
  login: 'login',
  recommendSupplier: 'recommend-supplier',
  businessCard: 'business-card',
  followShop: 'follow-shop',
  latestView: 'latest-view',
  shop: 'shop',
  itemDetail: 'item-detail',
  shopInfo: 'shop-info',
  myApply: 'my-apply',
  itemFavorite: 'item-favorite',
  noticeList: 'notice-list',
  noticeDetail: 'notice-detail',
  shareItemList: 'share-item-list',
  tradeCreate: 'trade-create',
}
