export default {
  // 首页信息
  homeInfo: '/home/info',
  // 订单初始化
  orderInit: '/order/submit-init',
  // 提交订单
  orderSubmit: '/order/submit',
  // 订单价格
  orderPrice: '/price/calc-proposed-price',
  // 订单列表
  orderList: '/order/list',
  // 订单详情
  orderDetail: '/order/detail',
  // 订单验布报告
  viewReport: '/report/report-by-order',
  // 支付详情
  detailForPay: '/order/detail-for-pay',
  // 去支付接口
  createPayment: '/pay/createPayment',
  // 获取签名
  signPay: '/cashier/pay',
  // 支付扫码
  scanPay: '/cashier/index.html',
  // 支付回调
  returnPay: '/weChatPay/return',
  // 取消验布
  cancelOrder: '/order/cancel',
  // 获取地址类型
  addressType: '/customer-address/type-list',
  // 地址列表
  addressList: '/customer-address/list',
  // 增加地址
  addressAdd: '/customer-address/add',
  // 修改地址
  addressUpdate: '/customer-address/update',
  // 删除地址
  addressDelete: '/customer-address/delete',
  // 设置默认地址
  addressDefault: '/customer-address/default',
  // 获取地址详情
  addressDetail: '/customer-address/detail',
  // 客户详情
  customerDetail: '/customer/detail',
}
